In [ ]:
# Assessing geospatial distribution of population statistics.

Script to include :
 - external modules imported at the beginning of the script
 - functions that have been written to help ensure code is readable and reproducable - include docstring - explanation, different input parameters, and outputs
 - embedded comments
 -

External module import:

In [97]:
# external modules:
import os # Review
import pandas as pd
import geopandas as gpd
import shapely
#import cartopy
#import pyepsy
#import rasterstats

#import matplotlib.pyplot as plt
#plt.ion() # make the plot interactive

Import Data
- Census data csv
- Data zone shapefile

In [98]:
zones = gpd.read_file('data_files/DZ2021.shp') # import data zones shapefile as zones
census = pd.read_csv('data_files/Census.csv') # import census data csv file as census

Join Census Data to Data Zones
DZ_2021_Code from census will join with DZ2021_cd from zones

In [99]:
zones.head() # identify header that will join with census data

,DZ2021_cd,DZ2021_nm,LGD2014_nm,Area_ha,Perim_km,geometry
0,N20000001,Dunsilly_A1,Antrim and Newtownabbey,2070.68,22.93,"POLYGON ((319580.264 396993.361, 319573.665 39..."
1,N20000002,Dunsilly_B1,Antrim and Newtownabbey,1253.69,19.14,"POLYGON ((323772.447 393378.876, 323764.289 39..."
2,N20000003,Dunsilly_A2,Antrim and Newtownabbey,792.91,15.50,"POLYGON ((305377.841 395055.242, 305378.841 39..."
3,N20000004,Dunsilly_A3,Antrim and Newtownabbey,1100.52,17.90,"POLYGON ((311500.959 395028.333, 311510.728 39..."
4,N20000005,Dunsilly_B2,Antrim and Newtownabbey,1740.82,21.93,"POLYGON ((323772.447 393378.876, 323784.201 39..."

In [100]:
census.head() # identify header that will join with census data

,ID,DZ_2021_Code,DZ_2021_Name,popn,le_4_yrs,PC_le_4_yrs,ge_66_yrs,PC_ge_66_yrs,working_age,employed,unemployed,PC_no_qual,PC_rented,PC_depriv_hholds,LTHC,PC_LTHC
0,1,N20000001,Dunsilly_A1,738,50,6.8,105,14.23,468,395,11,19.46,7.6,12.4,221,29.95
1,2,N20000002,Dunsilly_B1,331,9,2.7,65,19.64,211,187,6,14.69,13.5,18.9,109,32.93
2,3,N20000003,Dunsilly_A2,364,17,4.7,80,21.98,215,185,9,19.41,14.8,20.3,108,29.67
3,4,N20000004,Dunsilly_A3,663,31,4.7,112,16.89,381,324,12,14.40,10.9,12.3,193,29.15
4,5,N20000005,Dunsilly_B2,676,29,4.3,120,17.75,421,353,10,16.99,8.7,15.7,205,30.33

In [101]:
census = census.rename({'DZ_2021_Code' : 'DZ2021_cd'}, axis=1) #rename census.DZ_2021_Code to DZ2021_cd to match zones
census.head() # error check

,ID,DZ2021_cd,DZ_2021_Name,popn,le_4_yrs,PC_le_4_yrs,ge_66_yrs,PC_ge_66_yrs,working_age,employed,unemployed,PC_no_qual,PC_rented,PC_depriv_hholds,LTHC,PC_LTHC
0,1,N20000001,Dunsilly_A1,738,50,6.8,105,14.23,468,395,11,19.46,7.6,12.4,221,29.95
1,2,N20000002,Dunsilly_B1,331,9,2.7,65,19.64,211,187,6,14.69,13.5,18.9,109,32.93
2,3,N20000003,Dunsilly_A2,364,17,4.7,80,21.98,215,185,9,19.41,14.8,20.3,108,29.67
3,4,N20000004,Dunsilly_A3,663,31,4.7,112,16.89,381,324,12,14.40,10.9,12.3,193,29.15
4,5,N20000005,Dunsilly_B2,676,29,4.3,120,17.75,421,353,10,16.99,8.7,15.7,205,30.33

In [102]:
census_zones = gpd.GeoDataFrame(pd.merge(zones, census, on='DZ2021_cd', how='outer').fillna(0)) # join census and zones based on common column DZ2021_cd using an outer join and filling NA values.

census_zones # check output

,DZ2021_cd,DZ2021_nm,LGD2014_nm,Area_ha,Perim_km,geometry,ID,DZ_2021_Name,popn,le_4_yrs,...,ge_66_yrs,PC_ge_66_yrs,working_age,employed,unemployed,PC_no_qual,PC_rented,PC_depriv_hholds,LTHC,PC_LTHC
0,N20000001,Dunsilly_A1,Antrim and Newtownabbey,2070.68,22.93,"POLYGON ((319580.264 396993.361, 319573.665 39...",1,Dunsilly_A1,738,50,...,105,14.23,468,395,11,19.46,7.6,12.4,221,29.95
1,N20000002,Dunsilly_B1,Antrim and Newtownabbey,1253.69,19.14,"POLYGON ((323772.447 393378.876, 323764.289 39...",2,Dunsilly_B1,331,9,...,65,19.64,211,187,6,14.69,13.5,18.9,109,32.93
2,N20000003,Dunsilly_A2,Antrim and Newtownabbey,792.91,15.50,"POLYGON ((305377.841 395055.242, 305378.841 39...",3,Dunsilly_A2,364,17,...,80,21.98,215,185,9,19.41,14.8,20.3,108,29.67
3,N20000004,Dunsilly_A3,Antrim and Newtownabbey,1100.52,17.90,"POLYGON ((311500.959 395028.333, 311510.728 39...",4,Dunsilly_A3,663,31,...,112,16.89,381,324,12,14.40,10.9,12.3,193,29.15
4,N20000005,Dunsilly_B2,Antrim and Newtownabbey,1740.82,21.93,"POLYGON ((323772.447 393378.876, 323784.201 39...",5,Dunsilly_B2,676,29,...,120,17.75,421,353,10,16.99,8.7,15.7,205,30.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3775,N20003776,Ards_Peninsula_N2,Ards and North Down,30.72,3.00,"POLYGON ((359752.134 351035.673, 359759.06 351...",3776,Ards_Peninsula_N2,448,11,...,53,11.83,298,229,8,13.28,18.5,26.2,153,34.08
3776,N20003777,Ards_Peninsula_N3,Ards and North Down,7.41,1.21,"POLYGON ((359710.93 351090.923, 359759.06 3510...",3777,Ards_Peninsula_N3,448,23,...,78,17.41,271,152,17,29.89,50.3,43.4,214,47.66
3777,N20003778,Ards_Peninsula_N4,Ards and North Down,18.28,3.06,"POLYGON ((359863.411 350571.537, 359828.275 35...",3778,Ards_Peninsula_N4,430,17,...,101,23.49,251,193,6,21.89,38.2,29.9,165,38.37
3778,N20003779,Ards_Peninsula_N5,Ards and North Down,13.15,2.40,"POLYGON ((359671.758 349967.45, 359669.807 349...",3779,Ards_Peninsula_N5,447,10,...,116,25.95,277,158,12,26.70,52.6,41.8,206,46.09
3779,N20003780,Ards_Peninsula_L4,Ards and North Down,1722.81,35.89,"POLYGON ((362526.629 345473.515, 362523.318 34...",3780,Ards_Peninsula_L4,449,21,...,115,25.61,263,207,5,17.23,17.0,19.3,177,39.60

Population Density

In [81]:
census_zones.to_file('census_zones.shp')

C:\Users\jasmi\AppData\Local\Temp\ipykernel_18612\1608753471.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  census_zones.to_file('census_zones.shp')
C:\Users\jasmi\anaconda3\envs\egm722geospatial\Lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'DZ_2021_Name' to 'DZ_2021_Na'
  ogr_write(
C:\Users\jasmi\anaconda3\envs\egm722geospatial\Lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'PC_le_4_yrs' to 'PC_le_4_yr'
  ogr_write(
C:\Users\jasmi\anaconda3\envs\egm722geospatial\Lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'PC_ge_66_yrs' to 'PC_ge_66_y'
  ogr_write(
C:\Users\jasmi\anaconda3\envs\egm722geospatial\Lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'working_age' to 'working_ag'
  ogr_write(
C:\Users\jasmi\anaconda3\envs\egm722geospatial\Lib\site-packages\pyogrio\raw.py:733: RuntimeWarning: Normalized/laundered field name: 'PC_depriv_hholds' to 'PC_depriv_'
  ogr_write(

In [103]:
census_zones=census_zones.to_crs(epsg=29902)

In [82]:
# population density
# crs metric - ITM
# calculate area of data zones - datazones area in km
# calulcate population density -  
# error check?

In [83]:
if census_zones.crs is None: # ensure census_zones has projected CRS for area calculation 
    raise ValueError ("No CRS found. Please set CRS before calculating area.")
    
if census_zones.crs.is_geographic: #reproject to CRS in meters (e.g. mercator) - Northern Ireland EPSG:29902
    census_zones=census_zones.to_crs(epsg=29902)

In [104]:
for ind, row in census_zones.iterrows():
    census_zones.loc[ind,'Area_KM2']=row['geometry'].area/1000000,
    # creates new column 'Area_KM2' by taking geometry m and converting it to area in km2)

In [93]:
def add_area_km2(gdf):
    if 'geometry' not in gdf.columns:
        raise ValueError("GeoDataFrame must have a 'geometry' column.")
        gdf[Area_KM2]=gdf.geometry.area/1000000
        return gdf

census_zones = add_area_km2(census_zones)

In [105]:
census_zones.columns

Index(['DZ2021_cd', 'DZ2021_nm', 'LGD2014_nm', 'Area_ha', 'Perim_km',
       'geometry', 'ID', 'DZ_2021_Name', 'popn', 'le_4_yrs', 'PC_le_4_yrs',
       'ge_66_yrs', 'PC_ge_66_yrs', 'working_age', 'employed', 'unemployed',
       'PC_no_qual', 'PC_rented', 'PC_depriv_hholds', 'LTHC', 'PC_LTHC',
       'Area_KM2'],
      dtype='str')

In [106]:
if "popn" not in census_zones.columns: # validate popn exists
    raise KeyError ("'popn' column not found in dataset")

census_zones['PopnDens']=census_zones['popn']/census_zones['Area_KM2'] # create population density column from  popn / area_km2

print(census_zones.head())

   DZ2021_cd    DZ2021_nm               LGD2014_nm  Area_ha  Perim_km  \
0  N20000001  Dunsilly_A1  Antrim and Newtownabbey  2070.68     22.93
1  N20000002  Dunsilly_B1  Antrim and Newtownabbey  1253.69     19.14
2  N20000003  Dunsilly_A2  Antrim and Newtownabbey   792.91     15.50
3  N20000004  Dunsilly_A3  Antrim and Newtownabbey  1100.52     17.90
4  N20000005  Dunsilly_B2  Antrim and Newtownabbey  1740.82     21.93

                                            geometry  ID DZ_2021_Name  popn  \
0  POLYGON ((319580.264 396993.361, 319573.665 39...   1  Dunsilly_A1   738
1  POLYGON ((323772.447 393378.876, 323764.289 39...   2  Dunsilly_B1   331
2  POLYGON ((305377.841 395055.242, 305378.841 39...   3  Dunsilly_A2   364
3  POLYGON ((311500.959 395028.333, 311510.728 39...   4  Dunsilly_A3   663
4  POLYGON ((323772.447 393378.876, 323784.201 39...   5  Dunsilly_B2   676

   le_4_yrs  ...  working_age  employed  unemployed PC_no_qual  PC_rented  \
0        50  ...          468       395          11      19.46        7.6
1         9  ...          211       187           6      14.69       13.5
2        17  ...          215       185           9      19.41       14.8
3        31  ...          381       324          12      14.40       10.9
4        29  ...          421       353          10      16.99        8.7

   PC_depriv_hholds  LTHC  PC_LTHC   Area_KM2   PopnDens
0              12.4   221    29.95  20.706758  35.640539
1              18.9   109    32.93  12.536913  26.402033
2              20.3   108    29.67   7.929093  45.906889
3              12.3   193    29.15  11.005218  60.244152
4              15.7   205    30.33  17.408166  38.832350

[5 rows x 23 columns]

In [110]:
#find range of population density
popdens_data = census_zones['PopnDens'].dropna() # remove n/a values
min_val = popdens_data.min() # find minimum value in popndens column
max_val = popdens_data.max() # find maximum value in popndens column

print(f"range of {'PopnDens'}: min = {min_val}, max = {max_val}")

range of PopnDens: min = 4.043724559686971, max = 25527.845791342395

In [112]:

def popdens_category(value):
    if value < 300:
        return "Low"
    elif 300 <= value < 10000:
        return "Medium"
    else:
        return "High"

# Create a new column using map()
census_zones['PopDens_Category'] = census_zones['PopnDens'].map(popdens_category) #selects PopDens column and applies popdens function to each value, stored in new column PopDens_Category

In [113]:
census_zones.head()

,DZ2021_cd,DZ2021_nm,LGD2014_nm,Area_ha,Perim_km,geometry,ID,DZ_2021_Name,popn,le_4_yrs,...,employed,unemployed,PC_no_qual,PC_rented,PC_depriv_hholds,LTHC,PC_LTHC,Area_KM2,PopnDens,PopDens_Category
0,N20000001,Dunsilly_A1,Antrim and Newtownabbey,2070.68,22.93,"POLYGON ((319580.264 396993.361, 319573.665 39...",1,Dunsilly_A1,738,50,...,395,11,19.46,7.6,12.4,221,29.95,20.706758,35.640539,Low
1,N20000002,Dunsilly_B1,Antrim and Newtownabbey,1253.69,19.14,"POLYGON ((323772.447 393378.876, 323764.289 39...",2,Dunsilly_B1,331,9,...,187,6,14.69,13.5,18.9,109,32.93,12.536913,26.402033,Low
2,N20000003,Dunsilly_A2,Antrim and Newtownabbey,792.91,15.50,"POLYGON ((305377.841 395055.242, 305378.841 39...",3,Dunsilly_A2,364,17,...,185,9,19.41,14.8,20.3,108,29.67,7.929093,45.906889,Low
3,N20000004,Dunsilly_A3,Antrim and Newtownabbey,1100.52,17.90,"POLYGON ((311500.959 395028.333, 311510.728 39...",4,Dunsilly_A3,663,31,...,324,12,14.40,10.9,12.3,193,29.15,11.005218,60.244152,Low
4,N20000005,Dunsilly_B2,Antrim and Newtownabbey,1740.82,21.93,"POLYGON ((323772.447 393378.876, 323784.201 39...",5,Dunsilly_B2,676,29,...,353,10,16.99,8.7,15.7,205,30.33,17.408166,38.832350,Low

Website to determine UTM zone: https://mangomap.com/robertyoung/maps/69585/what-utm-zone-am-i-in-#

In [ ]:
ni_utm = ccrs.UTM(29) #Universal Transverse Mercator reference system Northern Ireland lies in zone 29

Unemployment

In [ ]:
# unemployment rate 
# use economically active - unemployed / (employed + unemployed) * 100

In [ ]:
# map of unemployment rate per data zone